const plantImages: { [key: string]: any } = {
  'allium-ursinum-flower_01.jpg': require('../assets/images/plants/allium-ursinum-flower_01.jpg'),
  'allium-ursinum_01.jpg': require('../assets/images/plants/allium-ursinum_01.jpg'),
  'anemone-nemorosa-flower_01.jpg': require('../assets/images/plants/anemone-nemorosa-flower_01.jpg'),
  'anemone-nemorosa_01.jpg': require('../assets/images/plants/anemone-nemorosa_01.jpg'),
  'arctium-lappa-burr_01.jpg': require('../assets/images/plants/arctium-lappa-burr_01.jpg'),
  'arctium-lappa_01.jpg': require('../assets/images/plants/arctium-lappa_01.jpg'),
  'artemisia-vulgaris_01.jpg': require('../assets/images/plants/artemisia-vulgaris_01.jpg'),
  'artemisia-vulgaris_01.png': require('../assets/images/plants/artemisia-vulgaris_01.png'),
  'arum-maculatum-spathe_01.jpg': require('../assets/images/plants/arum-maculatum-spathe_01.jpg'),
  'arum-maculatum_01.jpg': require('../assets/images/plants/arum-maculatum_01.jpg'),
  'carex-pendula_01.jpg': require('../assets/images/plants/carex-pendula_01.jpg'),
  'chenopodium-album_01.jpg': require('../assets/images/plants/chenopodium-album_01.jpg'),
  'chenopodium-album_01.png': require('../assets/images/plants/chenopodium-album_01.png'),
  'galium-aparine_01.jpg': require('../assets/images/plants/galium-aparine_01.jpg'),
  'geranium-robertianum-flower_01.jpg': require('../assets/images/plants/geranium-robertianum-flower_01.jpg'),
  'geranium-robertianum_01.jpg': require('../assets/images/plants/geranium-robertianum_01.jpg'),
  'glechoma-hederacea_01.jpg': require('../assets/images/plants/glechoma-hederacea_01.jpg'),
  'impatiens-glandulifera-flower_01.jpg': require('../assets/images/plants/impatiens-glandulifera-flower_01.jpg'),
  'impatiens-glandulifera_01.jpg': require('../assets/images/plants/impatiens-glandulifera_01.jpg'),
  'matricaria-discoidea_01.jpg': require('../assets/images/plants/matricaria-discoidea_01.jpg'),
  'oxalis-acetosella_01.jpg': require('../assets/images/plants/oxalis-acetosella_01.jpg'),
  'plantago-major_01.jpg': require('../assets/images/plants/plantago-major_01.jpg'),
  'prunus-avium-leaves_01.jpg': require('../assets/images/plants/prunus-avium-leaves_01.jpg'),
  'prunus-spinosa-leaves_01.jpg': require('../assets/images/plants/prunus-spinosa-leaves_01.jpg'),
  'rubus-fruticosus_01.jpg': require('../assets/images/plants/rubus-fruticosus_01.jpg'),
  'rumex-obtusifolius_01.jpg': require('../assets/images/plants/rumex-obtusifolius_01.jpg'),
  'stellaria-media_01.jpg': require('../assets/images/plants/stellaria-media_01.jpg'),
  'urtica-dioica_01.jpg': require('../assets/images/plants/urtica-dioica_01.jpg'),
};

export default plantImages;
